baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'WoldTech'
theme = 'binario'

[Params.Share]
  facebook = true
  twitter = true
  reddit = true
  telegram = true
  linkedin = true
  vk = true
  pocket = false
  pinterest = false

[Params.Social]
  email = "philip@philipwoldhek.nl"
  twitter = "WoldHack"
  linkedin = "philip-woldhek"
  github = "11philip22"
  stackoverflow = "11783384"
