baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'WoldTech'
theme = 'binario'

[Params.Share]
  facebook = true
  twitter = true
  reddit = true
  telegram = true
  linkedin = true
  vk = true
  pocket = false
  pinterest = false

[Params.Social]
  email = "philip@philipwoldhek.nl"
  twitter = "WoldHack"
  linkedin = "philip-woldhek"
  github = "11philip22"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 2

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = "native"             # Choose a theme (e.g., monokai, dracula, github, etc.)
    lineNos = false              # Enable line numbers (optional)
    lineNumbersInTable = false   # Makes line numbers cleaner (optional)