baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'woldhack'
theme = 'woldhack'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 4

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = "native"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false